version: "3.5"
services:
  jaffle_shop:
    image: jaffle_shop
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    ports: 
      - "8080:8080"